### ISSUE TITLE
Don't systematicaly load .env

### ISSUE THREAD

**Issue by r4iponce** [redds-be/reddlinks#28]
Docker should source .env and app load from environment. Volume for .env config is really crappy (https://github.com/redds-be/reddlinks/blob/3b4f7805825d7bdcf3bde42abb44eb9ad027a3a5/docker/docker-compose.yml#L40C1-L40C19)

**Comment by redds-be** [comment]
The change I'll be more likely to implement would be bypassing godotenv loading of `.env` when .env isn't found (either by using os.Stat or ignoring godotenv.Load() returned error) and throwing errors only if needed env variables aren't set, this would allow the use of env variables with `docker-compose.yml`/`docker run` as well as the use of `Environment=` inside a systemd unit. I would also modify `docker-compose.yml` to configure the env variables there instead of using a .env volume.

This is just a suggestion for myself and other suggestions are welcome.
